### ISSUE TITLE
New Chickens

### ISSUE THREAD

**Issue by Thiana** [GenDeathrow/MoreChickens#11]
Could you please consider dirt/gravel/cobble chickens to go along with the sand ones? Possibly skip the dirt one in favor of a sand/gravel + manure = dirt recipe.

Also, since uranium is available could we also have Resonating Ore (or liquid egg) chickens for Deep Resonance?

Thanks

**Comment by GenDeathrow** [comment]
I avoid dealing with vanilla blocks as I mainly add on modded blocks. but I will look into the second addition as a possibility.
