### ISSUE TITLE
ender io chickens

### ISSUE THREAD

**Issue by bogger33** [GenDeathrow/MoreChickens#12]
I would love if enderio alloys could be added to this. In fact, I would be willing to make the pull request myself. Do you accept/want pull requests?

**Comment by GenDeathrow** [comment]
I will accept pull request, but dont be offended if I don't use every thing or change stuff.  Making the chickens isn't hard. its the textures I hate. Just do your best to make them very different from my plain ol textures. So ppl don't get confused.

**Comment by bogger33** [comment]
great, and I won't be offended at all. I might do some other mods as well then, but I understand the the final call is up to you, of course.

**Comment by bogger33** [comment]
Have you had a chance to look at my pull request yet? I don't meant to hassle you, but I'd like to make one for thermal expansion and I thought it'd make sense to wait for feedback first.

**Comment by GenDeathrow** [comment]
Tbh I didnt even see this pop up.. ill take a look later on tonight. Thanks.

**Comment by bogger33** [comment]
Great, thanks!

**Comment by bogger33** [comment]
uh, did you forget?

**Comment by GenDeathrow** [comment]
I didn't forget, Im just part of a big project, and have 3 old mods that are needed updates, as a priority.

**Comment by bogger33** [comment]
oh okay, sorry. I was being impatient.

**Comment by GenDeathrow** [comment]
It looks good from what I have seen. I will do my best to get it this week. I ve just had some programs kicking my butt. Its ok I said I would have gotten it that day. and I just pushed it off for a bit. I will do my best.

**Comment by bogger33** [comment]
Alright, great, thanks! I'll work on more chickens then

**Comment by bogger33** [comment]
i added a thermal expansion pull request as well now. if there's any mods you would want me to try and tackle, i wouldn't mind doing that either, since you said you don't like making the textures.

**Comment by GenDeathrow** [comment]
I appreciate all the work you have put in. I got to do some tweaking to my base code, and try to push this as soon as thats done.

**Comment by GenDeathrow** [comment]
ok .. so I have finally got it in my dev enviroment.. will try and push an update today

**Comment by GenDeathrow** [comment]
Also I redoing the registering, to be a bit more simple.

**Comment by GenDeathrow** [comment]
Ok I have literally worked on this all day.. its too late to push an update with out proper testing. I believe everything is working. If you can test this for me I be grateful. Just remember to regenerate your config files "morechickens.cfg" & possible "chickens.cfg" to make sure everything is working right. 

If its a Dev enviroment it will print out a lot of debug code.

**Comment by bogger33** [comment]
I'll test it right now! Thanks!

By the way, I'm working on some textures for commonly used gems like e.g. ruby, perdiot, etc.

**Comment by bogger33** [comment]
The soul sand chicken has no legs and beak, is that intentional?

**Comment by bogger33** [comment]
The Basalz Rod chicken egg has the wrong color scheme, it has the same as the blitz rod chicken. That's actually my bad, apparently I just hadn't noticed before. Sorry about that.

The correct colors should be something like:
Outline: #980000
Background: #6E6664

**Comment by bogger33** [comment]
Beyond that it all looks good and in working order!

**Comment by GenDeathrow** [comment]
Ok ill make that change. Yes soul sand chickens where meant to be creepy looking.. floating. Tried to give a peeling face look.

**Comment by bogger33** [comment]
ah yeah, I thought so, just wanted to make sure.

**Comment by GenDeathrow** [comment]
bogger do me a favor, make your self a chicken of your skin, much like I did with chickenosto(Darkosto) and funwaychick(Funwayguy).

**Comment by bogger33** [comment]
Wow, thanks! I appreciate that!

I've added it to my pull request now, I hope that's okay. I made it drop a grass block since that's very appropriate to my skin, but I don't mind if you want to change it to something else.

**Comment by GenDeathrow** [comment]
Closing this since most of this is done...
