### ISSUE TITLE
Energetic Alloy / Vibrant Alloy chickens have swapped textures

### ISSUE THREAD

**Issue by tofof** [GenDeathrow/MoreChickens#20]
Textures are swapped.

Energetic (orange) eggs -> energetic chickens (yellow-green skin) -> energetic alloy (orange ingots).
Vibrant (yellow-green) eggs -> vibrant chickens (orange skin)  -> vibrant alloy (yellow green ingots), 

![Image of vibrant-colored energetic chicken](http://i.imgur.com/s6RyNM7.png?1)

**Comment by GenDeathrow** [comment]
It will get fixed up next update. Someone already made a push update and its fixed on a dev branch

**Comment by GenDeathrow** [comment]
https://github.com/GenDeathrow/MoreChickens/commit/a46d421f07bca43c01199209520f6bd3096be123

update will be out today
