### ISSUE TITLE
Curse mod description inaccuracies

### ISSUE THREAD

**Issue by bogger33** [GenDeathrow/MoreChickens#23]
A few things that could be updated on the curse description:

-add aluminium to base metals and remove from Immersive Engineering category

-add Saltpeter and sulfur to Base Metals (possibly rename the category to base materials?)

-Electrical Steel is misspelled (Electrical Stee)

Also this sentence: "It expands on the his mod to include support for both" - remove either the "the" or the "his"

**Comment by GenDeathrow** [comment]
Ill get on this.

**Comment by bogger33** [comment]
by the way, is there any mods you'd like me to make textures for? I'm working on extra utilities right now
