### ISSUE TITLE
Chicken breeding recipes

### ISSUE THREAD

**Issue by withercrusher** [GenDeathrow/MoreChickens#26]
Hey,

I have a problem i don't have breeding recipes in my JEI.

And when i hover over eggs it says "Tooltip error see log"
Versions of my mods:
chickens-4.2.2
MoreChickens-1.10.2-1.1.3
hatchery-1.10.2-0.3.17
jei_1.10.2-3.14.7.420

**Comment by GenDeathrow** [comment]
have you tried updating the more chickens to the latest?

**Comment by withercrusher** [comment]
Yes, i did

**Comment by GenDeathrow** [comment]
From what you posted at the top your 2-3 versions behind. also is this a mod pack or a something you made?

**Comment by withercrusher** [comment]
Something i made

**Comment by withercrusher** [comment]
Newest version is from 3 days ago
I had this problem like week ago

**Comment by withercrusher** [comment]
Nope
I still have my problem

**Comment by GenDeathrow** [comment]
Thier is a log under logs/morechickens/
Use pastebin and send me that log. Did you modify the chickens config?
If you didn't, delete chickens.cfg and morechickens.cfg

**Comment by withercrusher** [comment]
https://pastebin.com/EiDGXtBR

**Comment by withercrusher** [comment]
I only changed that chickens make baby when they breed

**Comment by GenDeathrow** [comment]
ok in your logs there should be a latest log, it should have the errors in it,  copy that log for me. Technically if failing like this, its getting errors. but more chickens isn't throwing any real errors. (Ignore the errors it says its throwing). The only reason it would be throwing those errors is if its getting a null error. Did you try deleting your chickens and morechickens config files and let them regenerate?

**Comment by withercrusher** [comment]
Deleting config doesn't work

**Comment by withercrusher** [comment]
https://pastebin.com/h7UDBC3g

**Comment by withercrusher** [comment]
I can't put it on pastebin it's too big
I don't know what to do

**Comment by GenDeathrow** [comment]
well if you look in that file there is going to be a section that shows a tooltip error, it will be long because it repeats over and over agian. if you send me a small portion of the section I may be able to see whats crashing.

**Comment by GenDeathrow** [comment]
but something is happening to the chickens loading, and tbh I have no idea whats going on. you could try starting up without loading the world and just send me the load up log(latest).. you can also drag and drop the file.. but I still need the tool tip error if you can send it to me. you will get the error when you mouse over the egg.

Im going to be gone the rest of the day.. the other thing to try is make sure your on the latest version of java 8, and try loading the game with just chickens and more chickens installed and see if you get the same issue.

**Comment by withercrusher** [comment]
https://pastebin.com/7XJUANux

**Comment by GenDeathrow** [comment]
Are you sure your using "chickens-4.3.2".  I think you missed the line above that one that actually gave the error,.

**Comment by withercrusher** [comment]
ok i updated chickens and i'm fine
