### ISSUE TITLE
Default config generation is buggy

### ISSUE THREAD

**Issue by Gamewalker** [GenDeathrow/MoreChickens#3]
Hey,
if you generate a new config file, you will get this for botania:
 ```java
terrasteelchicken {
    # Item amount to be laid/dropped. [range: 1 ~ 64, default: 1]
    I:dropItemAmount=1

    # Item amount to be laid/dropped. [range: -2147483648 ~ 2147483647, default: 4]
    I:dropItemMeta=4

    # Item name to be laid/dropped. [default: botania:manaResource]
    S:dropItemName=botania:manaResource

    # Item amount to be laid/dropped. [range: 1 ~ 64, default: 1]
    I:eggItemAmount=1

    # Item amount to be laid/dropped. [range: -2147483648 ~ 2147483647, default: 4]
    I:eggItemMeta=4

    # Item name to be laid/dropped. [default: botania:manaResource]
    S:eggItemName=botania:manaResource

    # Is chicken enabled? [default: true]
    B:enabled=true

    # Scale time to lay an egg. [range: 0.01 ~ 100.0, default: 1.0]
    S:layCoefficient=1.0

    # First parent, empty if it's base chicken. [default: EnderChicken]
    S:parent1=EnderChicken

    # First parent, empty if it's base chicken. [default: pCrystalChicken]
    S:parent2=pCrystalChicken

    # Chicken spawn type, can be: NORMAL,SNOW,NONE,HELL [default: NONE]
    S:spawnType=NONE
}
```

~~here you can see the dopped item is defined as:
S:dropItemName=botania:manaResource
S:eggItemName=botania:manaResource~~

~~And this is for Terra, Mana and Elementium so the chicken drops them randomly I think.~~
My Manasteel Chicken dropped Elementium Ingots.

**Comment by Gamewalker** [comment]
```java
elementiumchicken {
    # Item amount to be laid/dropped. [range: 1 ~ 64, default: 1]
    I:dropItemAmount=1

    # Item amount to be laid/dropped. [range: -2147483648 ~ 2147483647, default: 19]
    I:dropItemMeta=19

    # Item name to be laid/dropped. [default: botania:manaResource]
    S:dropItemName=botania:manaResource

    # Item amount to be laid/dropped. [range: 1 ~ 64, default: 1]
    I:eggItemAmount=1

    # Item amount to be laid/dropped. [range: -2147483648 ~ 2147483647, default: 19]
    I:eggItemMeta=19

    # Item name to be laid/dropped. [default: botania:manaResource]
    S:eggItemName=botania:manaResource

    # Is chicken enabled? [default: true]
    B:enabled=true

    # Scale time to lay an egg. [range: 0.01 ~ 100.0, default: 1.0]
    S:layCoefficient=1.0

    # First parent, empty if it's base chicken. [default: manasteelchicken]
    S:parent1=manasteelchicken

    # First parent, empty if it's base chicken. [default: terrasteelchicken]
    S:parent2=terrasteelchicken

    # Chicken spawn type, can be: NORMAL,SNOW,NONE,HELL [default: NONE]
    S:spawnType=NONE
}
```
Elementium should be meta 7:
![2016-12-25_20 56 19](https://cloud.githubusercontent.com/assets/241821/21472664/acf73f20-cae4-11e6-94c3-78a44e2ed02f.png)

**Comment by GenDeathrow** [comment]
It looks like the config file got corrupted between updates, have you tried delete the config file and let it regenerate? and yes botania has a single item for all their ingots& nuggets.  and I am working off of Ore dictionary now, so it should be what ever the mod author sets.

**Comment by GenDeathrow** [comment]
and yes they are suppose to drop nuggets. but the other chicken prolly drops it because of a messed up version. and you running off the old configs.

**Comment by Gamewalker** [comment]
I already recreated it and it seems to work fine now. But why do you use terrasteel and manasteel ingots and for elementium nuggets? Shouldnt it be nuggets for balancing?

**Comment by GenDeathrow** [comment]
Im more tech, so I went by what a friend told me, and from what I know elementium is what you get after terrasteel and manasteel, much like the draconian and awaken draconican, the top tier is a nugget is just what I had set up, but all you have to do is change the item drop in the configs. I have set defaults, and  the configs allow you to set it up how you like.  

Hopefully I can come up with a better config system.
