### ISSUE TITLE
/give commands?

### ISSUE THREAD

**Issue by nxarmada** [GenDeathrow/MoreChickens#32]
what are the /give commands more chickens say to give a Yellorium Chicken

**Comment by GenDeathrow** [comment]
https://github.com/setycz/ChickensMod 

Scroll down to bottom of the page. But this may not work on version 1.11. as the integer id is replaced with a string id.. like "morechickens:yelloriumchicken" << cant remember if thats the exact id atm. But can go into your your minecraft instance logs folder, find chickens.gml open it with a text editor. it should list out its id's

**Comment by nxarmada** [comment]
Thanks...I am on 1.10.2 and I dont see anything related to Yellorium inside the file you suggested.

**Comment by GenDeathrow** [comment]
it should be "2100"

Starting ID...
https://github.com/GenDeathrow/MoreChickens/blob/master/src/main/java/com/gendeathrow/morechickens/modHelper/ExtremeReactorsAddon.java

each time I call this.. it increments +1
https://github.com/GenDeathrow/MoreChickens/blob/master/src/main/java/com/gendeathrow/morechickens/modHelper/ExtremeReactorsAddon.java#L27
