### ISSUE TITLE
Case issue in dependency list

### ISSUE THREAD

**Issue by PhoenixRiver** [GenDeathrow/MoreChickens#39]
Version: morechickens-1.12.2-3.0.0

These errors turn up on loading, I presume they would be an issue if I used Botania and / or EnderIO but, thankfully, I don't (though I guess someone will at some point). Either way they seem to be pretty easy to fix :)

[main/ERROR] [FML]: Unable to parse dependency for mod 'morechickens' with dependency string 'after:Botania'. The modId 'Botania' must be all lowercase.
[main/ERROR] [FML]: Unable to parse dependency for mod 'morechickens' with dependency string 'after:EnderIO'. The modId 'EnderIO' must be all lowercase.

Hope this helps.

**Comment by GenDeathrow** [comment]
super easy to fix. and they are fixed now.. next update....
