### ISSUE TITLE
Tech Reborn Chickens have in world textures but no item textures

### ISSUE THREAD

**Issue by sweetsosweet** [GenDeathrow/MoreChickens#45]
Hi, I'm using morechickens-1.12.2-3.1.0 with forge 14.23.2.2624 and the Tech Reborn chickens look fine when they are spawned in the world, but the item textures are all black/purple.

**Comment by timrwood** [comment]
These are probably Roost chicken textures, I opened an issue to track it here: https://github.com/timrwood/roost/issues/22

**Comment by sweetsosweet** [comment]
Oh woops! So sorry, obviously it's roost, don't know what I was thinking, lol. Thanks for opening the issue in the proper place. -_-;
