### ISSUE TITLE
crash duplicate names(1.10.2)

### ISSUE THREAD

**Issue by SDUBZ** [GenDeathrow/MoreChickens#5]
forge:1.10.2
chickens:4.2.1
more chickens:1.0.8

crash report
[crash-2017-01-04_03.44.11-client.txt](https://github.com/GenDeathrow/MoreChickens/files/682749/crash-2017-01-04_03.44.11-client.txt)

**Comment by GenDeathrow** [comment]
https://github.com/setycz/ChickensMod/issues/58
