### ISSUE TITLE
"Rendering Block Entity" Crash - Placing "Color" Egg in Egg Nest

### ISSUE THREAD

**Issue by Senzir** [GenDeathrow/MoreChickens#53]
Each time i try to hatch an "Color"(Red/Yellow/Orange) Egg with the Egg Nest my game Freezes/Crashs
wich also corrupts the save game (cant load it without instant Freeze/Crash even if i remove the mod)
lost 2 save games allready and tried it afterwards a few times in gamemode aswell

any help would be highly appreciated!

Minecraft Version: 1.12.2
Forge 14.23.4.2765
chickens                          | 6.1.0
morechickens                      | 3.1.0

Crash Log:
https://pastebin.com/ThhwF2z0

**Comment by GenDeathrow** [comment]
It seems like the new forge updates have messed up my rendering code. I know they fixed some issues with worlds not even loading in 64.. but this is new. I will take a look at it. Cant promise a quick fix.. you could go back a few updates I would suggest maybe version 62. That way you can attempt to save your world.

**Comment by Senzir** [comment]
Nice one !
 I had to go back to 55 wich is the one that is atleast required for the modpack( tried 62 wich didnt work) 
but after removing some mods that had some problems with a 67 savegame while running 55 and reinstalling them it works :D 
= closed ;)
