### ISSUE TITLE
Two Entries for "Is Enabled" in the JSON

### ISSUE THREAD

**Issue by KAfable** [GenDeathrow/MoreChickens#69]
### 
In the JSON, there are duplicate entries for whether it is enabled or not. Also there are keys with spaces.
```
  "morechickens:chromechicken": {
    "Name": "chromechicken",
    "Is Enabled": true,
    "Lay Coefficient": 1.0,
    "Lay Item": "gregtech:meta_item_1:10016",
    "Drop Item": "gregtech:meta_item_1:10016",
    "Spawn Type": "NONE",
    "Parent 1": "morechickens:tinchicken",
    "Parent 2": "morechickens:titaniumchicken",
    "name": "chromechicken",
    "is_enabled": true,
    "lay_coefficient": 1.0,
    "lay_item": {
      "itemID": "gregtech:meta_item_1",
      "metaID": 10016
    },
    "drop_item": {
      "itemID": "gregtech:meta_item_1",
      "metaID": 10016
    },
    "spawn_type": "NONE",
    "parent_1": "morechickens:tinchicken",
    "parent_2": "morechickens:titaniumchicken"
  },
```

**Comment by GenDeathrow** [comment]
It looks like there are duplicates of all the entries cause this was updated from an older version of chickens to a newer version config file.  Any of the ones with spaces/capitals are not valid anymore. IE: "Name", "Lay Coefficient", "Lay Item", "Drop Item", "Spawn Type", "Parent 1", "Parent 2". That config file is super old though, im actually surprised to see it.
