### ISSUE TITLE
Minor fix needed - Item XP missing Name (XP orb no RightClick)

### ISSUE THREAD

**Issue by MrAmericanMike** [GenDeathrow/MoreChickens#7]
Well I resumed it on the title to make it easy, but the XP Item doesn't has a name ;)

item.morechickens.solidxp.name is what it's showing ;)

**Comment by GenDeathrow** [comment]
crap, will have to wait for the next update. I have it in there but I forgot the ".name" in the lang file.

**Comment by MrAmericanMike** [comment]
I finally figured out how the XP thing work :) But a description like "Drop it on the world to get XP" would be cool also ;)

**Comment by GenDeathrow** [comment]
So I keep trying to figure out what you meant about the xp orbs and how to use them.  I just realized that I forgot to add the code in to be able to right click the xporb to get the exp.  It was suppose be added in, but some how got over looked.

**Comment by GenDeathrow** [comment]
Fixed in 0.2.3 its under beta if you dont see it.
