### ISSUE TITLE
Problem with Industrial Craft 2

### ISSUE THREAD

**Issue by Bricklou** [GenDeathrow/MoreChickens#75]
Hello,

I manage a modpack for a server and it seem that your mod have some issues with industrial craft 2.
When this one is not installed there is no issue but when I install I get theses errors:
![image](https://user-images.githubusercontent.com/15181236/84895302-6aba3480-b0a2-11ea-9529-3d50dd72e08f.png)

It happen only when you mod is installed otherwise I have no issue.
Have tou any idea why ?

**Comment by GenDeathrow** [comment]
I would have no clue. I have some powered blocks.. but not sure what would cause that. Id have to research it.

**Comment by Bricklou** [comment]
After more search all the afternoon, my friends and myself have found this was the mod `performant` which was the source of this problem and many others. So I'm closing this issue.

**Comment by GenDeathrow** [comment]
Thank you for figuring this out.
