### ISSUE TITLE
Client crash on dedicate server?

### ISSUE THREAD

**Issue by CelticChristoph** [GenDeathrow/MoreChickens#9]
Not really sure what caused my crash. I died, and then when I hit the "Respawn" key, things went crazy and then my game crashed.

MC: 1.10.2
Forge 12.18.3.2202

Tons of mods, too many to list here.

Crash report is here:
http://pastebin.com/hXweYXq3

**Comment by GenDeathrow** [comment]
This deals with hatchery.. what version are you on?

**Comment by CelticChristoph** [comment]
Yikes, I'm sorry. I meant to post this to the Hatchery GitHub, and just derped up.
Can you move it? Or is there a way to delete it and repost it on the correct GitHub?

Either way, I'm Hatchery version 0.2.2

MC - 1.10.2
Forge 12.18.3.2202

**Comment by GenDeathrow** [comment]
Sucks cause it should have been fixed in 0.2.2. But I seem to have anbissue with recreating it my server.  Ill look into it this week end

**Comment by GenDeathrow** [comment]
This issue should be fixed with 0.2.3 (its under beta version so you may not see it unless your settings show beta versions.)
